# Generated by Django 5.2.5 on 2025-09-07 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_post_fecha_post_creado_post_imagen_comentario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='max_comentarios',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
