# Generated by Django 5.2.5 on 2025-09-07 17:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_max_comentarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='autor',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='El nombre solo puede contener letras y espacios', regex='^[A-Za-zÁÉÍÓÚáéíóúÑñ\\s]+$')]),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='contenido',
            field=models.TextField(max_length=300),
        ),
    ]
