# Generated by Django 5.2.5 on 2025-08-17 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='resumen',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
